sudo: false
language: java
jdk:
 - oraclejdk8
 - oraclejdk11
 - openjdk8
 - openjdk11
before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
cache:
  directories:
  - $HOME/.m2
before_cache:
  - rm -rf $HOME/.m2/repository/uk/gov/nationalarchives/